### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by juniel03** [spacejake/android-age-estimator#1]
Hello spacejake can you teach me further on how you did the application?

**Comment by ganeshinde** [comment]
hey can you help me

**Comment by spacejake** [comment]
Hi, Sorry, this code is quite old and due to how much Android and Tensroflow has changed, it may be difficult to get this to work.

I suggest looking at TFlite models that do [face detection](https://github.com/pillarpond/face-recognizer-android) and age estimation, as well as tutorials on running TFLite models for vision on android.

Quick google search found [this one](https://github.com/shubham0204/Age-Gender_Estimation_TF-Android#-tensorflow-lite-models).

Good luck!
